version: "3.7"

services:
  # nginx-proxy:
  #   image: jwilder/nginx-proxy
  #   container_name: nginx-proxy
  #   ports:
  #     - "80:80"
  #     - "443:443"
  #   volumes:
  #     - /var/run/docker.sock:/tmp/docker.sock:ro
  #     - ./certs:/etc/nginx/certs
  #     - ./vhost:/etc/nginx/vhost.d
  #     - ./html:/usr/share/nginx/html
  # nginx-proxy-acme:
  #   image: nginxproxy/acme-companion
  #   container_name: nginx-proxy-acme
  #   volumes:
  #     - /var/run/docker.sock:/var/run/docker.sock:ro
  #     - ./certs:/etc/nginx/certs
  #     - ./vhost:/etc/nginx/vhost.d
  #     - ./html:/usr/share/nginx/html
  #     - ./acme:/etc/acme.sh
  #   environment:
  #     - NGINX_PROXY_CONTAINER=nginx-proxy
  #     - DEFAULT_EMAIL=ya.park@mail.utoronto.ca
  # frontend:
  #   image: ghcr.io/utsc-cscc09-programming-on-the-web/frontend-julia-yap
  #   container_name: frontend
  #   restart: always
  #   expose:
  #     - 80
  #   environment:
  #     - VIRTUAL_HOST=yeanio.studio
  #     - LETSENCRYPT_HOST=yeanio.studio
  #     - LETSENCRYPT_EMAIL=ya.park@mail.utoronto.ca
  # backend:
  #   image: ghcr.io/utsc-cscc09-programming-on-the-web/backend-julia-yap
  #   container_name: backend
  #   restart: always
  #   expose:
  #     - 3000
  #   environment:
  #     - VIRTUAL_HOST=api.yeanio.studio
  #     - LETSENCRYPT_HOST=api.yeanio.studio
  #     - LETSENCRYPT_EMAIL=ya.park@mail.utoronto.ca

  app:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/app
